add_lunch_combo liquid_d2vzw-userdebug
add_lunch_combo liquid_grouper-userdebug
add_lunch_combo liquid_i9300-userdebug
add_lunch_combo liquid_maguro-userdebug
add_lunch_combo liquid_n7000-userdebug
add_lunch_combo liquid_toro-userdebug
add_lunch_combo liquid_toroplus-userdebug
